language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t crmapj007/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true crmapj007/react-test npm test

after_success:
  - docker build -t crmapj007/multi-client ./client
  - docker build -t crmapj007/multi-nginx ./nginx
  - docker build -t crmapj007/multi-server ./server
  - docker build -t crmapj007/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push crmapj007/multi-client
  - docker push crmapj007/multi-nginx
  - docker push crmapj007/multi-server
  - docker push crmapj007/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: docker-react
  env: multiDocker-env
  bucket_name: elasticbeanstalk-eu-west-2-673896612194
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

